spring.application.name=TuristGuide
spring.datasource.url=jdbc:mysql://localhost:3306/attraction
spring.datasource.username=root
spring.datasource.password=Glostrup114!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
